apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app
  labels:
    app: messaging-app
    track: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
      track: blue
  template:
    metadata:
      labels:
        app: messaging-app
        track: blue
    spec:
      containers:
        - name: messaging-app
          image: icalistus/messaging-app:2.0
          imagePullPolicy: Always
          command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: messaging_app.settings
            - name: DEBUG
              value: "true"
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app
  labels:
    app: messaging-app
spec:
  type: ClusterIP
  selector:
    app: messaging-app
  ports:
    - port: 8000
      targetPort: 8000
